# platform :ios, '9.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ronaldo1' do
  # Pods for ronaldo1
  pod 'React', :path => '../node_modules/react-native/', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTCameraRoll',
    'RCTImage',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ronaldo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  # use_native_modules!
end

target 'ronaldo1-tvOS' do
  # Pods for ronaldo1-tvOS

  target 'ronaldo1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
